"""Estado inicial das tabelas

Revision ID: 2c27dfefd871
Revises: 
Create Date: 2025-11-02 17:34:21.742378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c27dfefd871'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('startups', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('startups', 'nome_da_empresa',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('startups', 'endereço',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'cnpj',
               existing_type=sa.TEXT(),
               type_=sa.String(length=18),
               nullable=False)
    op.alter_column('startups', 'ano_de_fundação',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('startups', 'site',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'rede_social',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'cadastrado_por',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'cargo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'e-mail',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'setor_principal',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'setor_secundario',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'fase_da_startup',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'colaboradores',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'publico_alvo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'modelo_de_negocio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'recebeu_investimento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'negócios_no_exterior',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'faturamento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'patente',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'já_pivotou?',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'comunidades',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('startups', 'solução',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_public_startups_cnpj'), 'startups', ['cnpj'], unique=True, schema='public')
    op.create_index(op.f('ix_public_startups_id'), 'startups', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_startups_nome_da_empresa'), 'startups', ['nome_da_empresa'], unique=False, schema='public')
    op.create_index(op.f('ix_public_startups_setor_principal'), 'startups', ['setor_principal'], unique=False, schema='public')
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_public_startups_setor_principal'), table_name='startups', schema='public')
    op.drop_index(op.f('ix_public_startups_nome_da_empresa'), table_name='startups', schema='public')
    op.drop_index(op.f('ix_public_startups_id'), table_name='startups', schema='public')
    op.drop_index(op.f('ix_public_startups_cnpj'), table_name='startups', schema='public')
    op.alter_column('startups', 'solução',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'comunidades',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'já_pivotou?',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'patente',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'faturamento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'negócios_no_exterior',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'recebeu_investimento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'modelo_de_negocio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'publico_alvo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'colaboradores',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'fase_da_startup',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'setor_secundario',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'setor_principal',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'e-mail',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'cargo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'cadastrado_por',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'rede_social',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'site',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'ano_de_fundação',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('startups', 'cnpj',
               existing_type=sa.String(length=18),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'endereço',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'nome_da_empresa',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('startups', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
